## Sid Meier's Civilization 4
## Copyright 2007 BUG Mod

#BUGFfH: Modified by Denev 2009/10/05
# MINOR_LEADERS_PEDIA 08/2013 lfgr: addded PEDIA_MINOR_LEADERS
#PEDIA_MAIN		= 200
#PEDIA_TECHS		= 201
#PEDIA_UNITS		= 202
#PEDIA_UNIT_UPGRADES	= 203
#PEDIA_UNIT_CATEGORIES	= 204
#PEDIA_PROMOTIONS	= 205
#PEDIA_PROMOTION_TREE	= 206
#PEDIA_BUILDINGS		= 207
#PEDIA_NATIONAL_WONDERS	= 208
#PEDIA_GREAT_WONDERS	= 209
#PEDIA_PROJECTS		= 210
#PEDIA_SPECIALISTS	= 211
#PEDIA_TERRAINS		= 212
#PEDIA_FEATURES		= 213
#PEDIA_BONUSES		= 214
#PEDIA_IMPROVEMENTS	= 215
#PEDIA_CIVS			= 216
#PEDIA_LEADERS		= 217
#PEDIA_TRAITS		= 218
#PEDIA_CIVICS		= 219
#PEDIA_RELIGIONS		= 220
#PEDIA_CORPORATIONS	= 221
#PEDIA_SPELLS	= 221
#PEDIA_ABILITIES   = 222
#PEDIA_CONCEPTS		= 223
#PEDIA_BTS_CONCEPTS	= 224
#PEDIA_HINTS		   	= 225
#PEDIA_SHORTCUTS 	= 226
#PEDIA_STRATEGY  	= 227
#PEDIA_MANA_NODES  = 228
PEDIA_MAIN,\
PEDIA_TECHS,\
PEDIA_UNITS,\
PEDIA_UNIT_UPGRADES,\
PEDIA_UNIT_CATEGORIES,\
PEDIA_PROMOTIONS,\
PEDIA_SPHERES,\
PEDIA_PROMOTION_TREE,\
PEDIA_EFFECTS,\
PEDIA_EQUIPMENTS,\
PEDIA_RACES,\
PEDIA_BUILDINGS,\
PEDIA_NATIONAL_WONDERS,\
PEDIA_GREAT_WONDERS,\
PEDIA_PROJECTS,\
PEDIA_SPECIALISTS,\
PEDIA_TERRAINS,\
PEDIA_FEATURES,\
PEDIA_UNIQUE_FEATURES,\
PEDIA_BONUSES,\
PEDIA_MANA_NODES,\
PEDIA_IMPROVEMENTS,\
PEDIA_CIVS,\
PEDIA_LEADERS,\
PEDIA_MINOR_LEADERS,\
PEDIA_TRAITS,\
PEDIA_CIVICS,\
PEDIA_RELIGIONS,\
PEDIA_SPELLS,\
PEDIA_ABILITIES,\
PEDIA_CONCEPTS,\
PEDIA_BTS_CONCEPTS,\
PEDIA_HINTS,\
PEDIA_SHORTCUTS,\
PEDIA_STRATEGY = range(200, 235)
#BUGFfH: End Modify

##--------	BUGFfH: Added by Denev 2009/10/08
TYPE_REGULAR,\
TYPE_NATIONAL,\
TYPE_TEAM,\
TYPE_WORLD = range(4)

TYPE_REGULAR,\
TYPE_EFFECT,\
TYPE_SPHERE,\
TYPE_EQUIPMENT,\
TYPE_GEAR,\
TYPE_RACE = range(6)

TYPE_REGULAR,\
TYPE_TEAM,\
TYPE_WORLD,\
TYPE_PROJECTTERRAFORM,\
TYPE_PROJECTGLOBAL,\
TYPE_SUMMONRITUAL = range(6)

TYPE_REGULAR,\
TYPE_SUMMON,\
TYPE_WORLDUNIT = range(3)

TYPE_REGULAR,\
TYPE_SPELLRESEARCH = range(2)

TYPE_REGULAR,\
TYPE_BONUS_MANA = range(2)

TYPE_REGULAR,\
TYPE_PRIMARY,\
TYPE_UNIQUE_FEATURES = range(3)
##--------	BUGFfH: End Add

# MINOR_LEADERS_PEDIA 08/2013 lfgr
TYPE_MAJOR,\
TYPE_MINOR = range( 2 )
# MINOR_LEADERS_PEDIA end
